language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: true

node_js:
  - "8.11.4"

before_script:
  - npm prun

script:
  - npm run build
  - npm test

after_success:
  - test $TRAVIS_BRANCH = "master" && npm run travis-deploy-once "npm run semantic-release"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
